// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeG-r5qMBGMFVujaPvJLIEanxlK6mnywg',
    appId: '1:434869041824:web:4a93590d93274b386e27c5',
    messagingSenderId: '434869041824',
    projectId: 'neurostellar-app',
    authDomain: 'neurostellar-app.firebaseapp.com',
    storageBucket: 'neurostellar-app.appspot.com',
    measurementId: 'G-DCZP9BFMT3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7zrmC_Ci1v1NIpFUfzyXTbLXKjQ2P62w',
    appId: '1:434869041824:android:2170a79b178fe6216e27c5',
    messagingSenderId: '434869041824',
    projectId: 'neurostellar-app',
    storageBucket: 'neurostellar-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9MBcts5ZS5y20S_pwZFXDM1Cda-0wrrg',
    appId: '1:434869041824:ios:42a208fa4818950d6e27c5',
    messagingSenderId: '434869041824',
    projectId: 'neurostellar-app',
    storageBucket: 'neurostellar-app.appspot.com',
    iosBundleId: 'com.example.colorchangingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9MBcts5ZS5y20S_pwZFXDM1Cda-0wrrg',
    appId: '1:434869041824:ios:72a07556fb305e206e27c5',
    messagingSenderId: '434869041824',
    projectId: 'neurostellar-app',
    storageBucket: 'neurostellar-app.appspot.com',
    iosBundleId: 'com.example.colorchangingapp.RunnerTests',
  );
}
